---
language: python
services: docker

before_script:
  - pip install -r requirements/dev.txt

script:
  - flake8
  - pytest --cov=./

after_script:
  - codecov

after_success:
  - docker build . -t "nl2go/ansible:$TRAVIS_BRANCH"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "nl2go/ansible:$TRAVIS_BRANCH"
