---
language: python
services: docker

env:
  - IMAGE_NAME='nl2go/ansible'

before_script:
  - pip install -r requirements/dev.txt

script:
  - flake8
  - pytest --cov=./

after_script:
  - codecov

after_success:
  - docker build . -t "$IMAGE_NAME:$TRAVIS_BRANCH" -t "$IMAGE_NAME:latest"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$IMAGE_NAME:$TRAVIS_BRANCH" && docker push "$IMAGE_NAME:latest"
