version: '3.5'
services:
  ansible:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - .:/ansible
      - $HOME$USERPROFILE/.ssh:/tmp/.ssh
    working_dir: /ansible
    networks:
      - ansible


networks:
  ansible:
    name: ansible
