version: '2'
services:
  ansible:
    build:
      context: ./
      dockerfile: Dockerfile
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ..:/projects
      - $HOME$USERPROFILE/.ssh:/tmp/.ssh
    working_dir: /projects
