version: '2.0'
services:
  ansible:
    image: nl2go/ansible:dev
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/ansible
      - $HOME$USERPROFILE/.ssh:/tmp/.ssh
